language: php

php:
  - 7.0

before_script:
  - composer install

after_success:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: 7.0

notifications:
  irc:
    channels:
      - "irc.quakenet.org#blar-dev"
