language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install

after_success:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

notifications:
  irc:
    channels:
      - "irc.quakenet.org#blar-dev"
